name: GuizhanLibPlugin
version: Build 62 (git aad97af)
main: net.guizhanss.minecraft.guizhanlib.GuizhanLib
description: A library plugin for Simplified Chinese Slimefun addons.
authors:
  - ybw0014
website: https://github.com/ybw0014/GuizhanLibPlugin
depend:
  - Slimefun
api-version: "1.18"
