# -*- coding: utf-8 -*-
"""将成就/进度相关插件文案汉化为简体中文（保留 NPC、mcMMO、XP 等常用专有名词）。"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# AdvancedAchievements config.yml 内 Goal / Message / DisplayName / Display
AA_TEXT: dict[str, str] = {
    "1MB Event Achievement!": "1MB 活动成就！",
    "Accident or intentional?": "意外还是故意？",
    "Adventurous Eater": "冒险食客",
    "Alchemist": "炼金师",
    "Angel": "天使",
    "Apiarist": "养蜂人",
    "Arrows Around the Place": "箭矢满天飞",
    "Bamboo Gardener": "竹林园丁",
    "Banner Designer": "旗帜设计师",
    "Bedrock Breaker": "基岩破坏者",
    "Bedrock Wannabe": "基岩崇拜者",
    "Big Walker": "远行旅人",
    "Blacksmith Apprentice": "铁匠学徒",
    "Blacksmith Legend": "铁匠传奇",
    "Bone Collector": "骨头收藏家",
    "Breeder": "畜牧新手",
    "Cake Boss": "蛋糕大亨",
    "Carrot on a Stick Master": "胡萝卜钓竿大师",
    "Carting Fan": "矿车爱好者",
    "Cobble Gobble!": "圆石吞噬者",
    "Cold Drink Supplier": "冷饮供应商",
    "DJ": "DJ",
    "Deep Miner": "深板岩矿工",
    "Diggy diggy hole": "挖呀挖呀挖",
    "Dirt, dirt and more dirt": "泥土，泥土，还是泥土",
    "Donator": "赞助者",
    "Environmentalist": "环保主义者",
    "Farmer": "农夫",
    "Feline Frenzy": "猫咪狂热",
    "Fire burn and cauldron bubble": "烈火烹油",
    "Fireman": "消防员",
    "First Hour": "第一小时",
    "First Milk": "第一次挤奶",
    "First Repair": "第一次修复",
    "First Snack": "第一口零食",
    "First Trade": "第一笔交易",
    "Frame Smasher": "展示框粉碎者",
    "Game Block Advance": "方块进阶",
    "Gardener": "园丁",
    "Glassbreaker": "玻璃粉碎者",
    "God of Slumber": "睡眠之神",
    "Good Choice": "明智之选",
    "Grand Fisher": "钓鱼大师",
    "Great Sailor": "伟大水手",
    "Haha! Surprise attack!": "哈！偷袭成功！",
    "Harvester Supreme": "收割至尊",
    "Hunter": "猎人",
    "Kangaroo": "袋鼠",
    "Keep exploring!": "继续探索！",
    "Llama Rider": "羊驼骑手",
    "Lord of the Land": "大地领主",
    "Neptune has asked for his trident back": "海神想要收回三叉戟",
    "Nether Prospector": "下界勘探者",
    "Ninja": "忍者",
    "No More mrfloris": "不再有 mrfloris",
    "Nomad": "流浪者",
    "Omelet Addict": "煎蛋成瘾者",
    "Overpowered": "过于强大",
    "Party Host": "派对主人",
    "Pickaxe Prodigy": "镐子天才",
    "Poing! (the noise of an arrow hitting a target)": "砰！（箭矢命中目标）",
    "Polluter": "污染者",
    "Poseidon": "波塞冬",
    "Potion Purger": "药水清道夫",
    "Potioneer": "药水师",
    "Powahhh!!!": "力量！！！",
    "Praying for Summer": "盼望夏天",
    "Pyroman": "纵火狂",
    "Pyrotechnist": "烟火师",
    "Really, it is time to stop leveling up now.. this is getting ridiculous": "说真的，该停手升级了……这太离谱了",
    "Receiver": "接收者",
    "Rest in Peace": "安息吧",
    "Safety First": "安全第一",
    "Scrambled Expert": "炒蛋专家",
    "Scribe": "抄写员",
    "Server Recognition": "服务器认可",
    "Server fan": "服务器粉丝",
    "Shieldsmith": "盾牌匠",
    "Sleepy Guy": "瞌睡虫",
    "Slowly climbing the ranks": "稳步攀升",
    "Snowmageddon": "雪灾",
    "Statistician": "统计学家",
    "Stone Addict": "石头成瘾者",
    "Stone God": "石头之神",
    "Stop damaging your gear!": "别再损坏装备了！",
    "Storage Expert": "仓储专家",
    "Superpowers! Let's go!": "超能力！冲！",
    "Swimmy Swimmy little fishes": "游啊游，小鱼儿",
    "Taiga Biome Master!": "针叶林大师！",
    "Taking in the old to create the new": "旧物新生",
    "Tamer": "驯兽师",
    "Teleport Man": "传送人",
    "Tetris Master": "俄罗斯方块大师",
    "The Angler": "垂钓者",
    "The Avener": "复仇者",
    "The Eyewitness": "目击者",
    "The Smelter": "熔炼师",
    "The Sticky Architect": "黏性建筑师",
    "The Stoner": "投石者",
    "The Walking Dead": "行尸走肉",
    "The birds, the bees, the sheep, the cows, the ark!": "飞禽走兽，诺亚方舟！",
    "The poor trees :(": "可怜的树 :(",
    "This sword is surpisingly sharp": "这把剑意外地锋利",
    "Time for Fish and Chips": "炸鱼薯条时间",
    "Time for a blast furnace?": "该用高炉了吗？",
    "Time for the olympics": "奥运会时间",
    "Treasure Hunter": "宝藏猎人",
    "Treehugger": "抱树者",
    "Village Protector": "村庄守护者",
    "Window Breaker": "窗户破坏者",
    "Winter Addict": "冬季成瘾者",
    "Workshop Tycoon": "工坊大亨",
    "You can never have too many crops": "作物永远不嫌多",
    "You know these are made to cut wood, right?": "你知道这是用来砍树的吧？",
    "You should really get some tools, you know?": "你真的该弄点工具了",
    "You've been grinding ranks too much": "你刷等级刷太多了",
    "Your bow must be enraged now...": "你的弓现在一定很生气……",
    "mcMMO level grinder": "mcMMO 等级狂人",
    "§1Wool Addict": "§1羊毛成瘾者",
    "§4Clumsy Guy": "§4笨拙家伙",
    "§4Rookie": "§4新手",
    "§5Wizard": "§5巫师",
    "Activate 10 mcMMO abilities": "激活 10 次 mcMMO 技能",
    "Bake 5 cakes.": "烘焙 5 个蛋糕。",
    "Break 10 ice blocks.": "破坏 10 个冰块。",
    "Break 100 glass blocks.": "破坏 100 个玻璃。",
    "Break 12 dripstone blocks.": "破坏 12 个滴水石块。",
    "Break 15 mossy cobblestone blocks.": "破坏 15 个苔石。",
    "Break 32 ice and/or snow.": "破坏 32 个冰和/或雪。",
    "Break 5 ancient debris.": "破坏 5 个远古残骸。",
    "Break 500 deepslate blocks.": "破坏 500 个深板岩。",
    "Break a block.": "破坏一个方块。",
    "Breed 10 bees.": "繁殖 10 只蜜蜂。",
    "Breed 3 cats.": "繁殖 3 只猫。",
    "Breed a sheep.": "繁殖一只羊。",
    "Brew a potion.": "酿造一瓶药水。",
    "Catch 100 fish.": "捕获 100 条鱼。",
    "Check your stats 10x.": "查看 10 次统计。",
    "Complete 20 advancements.": "完成 20 个进度。",
    "Craft 10 shields.": "合成 10 面盾牌。",
    "Craft 100 diamond swords.": "合成 100 把钻石剑。",
    "Craft 20 banners.": "合成 20 面旗帜。",
    "Craft a diamond sword.": "合成一把钻石剑。",
    "Defeat 10 witches.": "击败 10 个女巫。",
    "Defeat 25 endermen.": "击败 25 个末影人。",
    "Drink 100 potions.": "饮用 100 瓶药水。",
    "Drop 15 items.": "丢弃 15 个物品。",
    "Eat 10 suspicious stews.": "食用 10 碗迷之炖菜。",
    "Eat something.": "吃点东西。",
    "Edit 10 books.": "编辑 10 本书。",
    "Enchant 5 things.": "附魔 5 次。",
    "Fill 10 buckets with lava.": "装满 10 桶熔岩。",
    "Fill 10 buckets with water.": "装满 10 桶水。",
    "Fish a fish.": "钓一条鱼。",
    "Fly 100 blocks with an elytra.": "用鞘翅飞行 100 格。",
    "Get a treasure from the sea.": "从海中获取宝藏。",
    "Give 3 pets to friends.": "赠送 3 只宠物给好友。",
    "Hit 20 item frames with projectiles.": "用弹射物击中 20 个展示框。",
    "Hold the jump boost effect!": "获得跳跃提升效果！",
    "Kill a zombie.": "击杀一只僵尸。",
    "Kill the server Owner.": "击杀服务器服主。",
    "Launch fireworks 10 times.": "燃放 10 次烟花。",
    "Let an item break.": "让一件物品损坏。",
    "Milk a cow.": "给牛挤奶。",
    "Pick 40 items up.": "拾取 40 个物品。",
    "Place 10 honey blocks.": "放置 10 个蜂蜜块。",
    "Place 100 Stones.": "放置 100 个石头。",
    "Place 1000 stones.": "放置 1000 个石头。",
    "Place 200 bamboo.": "放置 200 根竹子。",
    "Place 25 crafting tables.": "放置 25 个工作台。",
    "Place 5 chests.": "放置 5 个箱子。",
    "Place 50 chests.": "放置 50 个箱子。",
    "Place 50 obsidian blocks.": "放置 50 个黑曜石。",
    "Play 10 music discs.": "播放 10 张唱片。",
    "Play an hour.": "游玩 1 小时。",
    "Play for 100 hours.": "游玩 100 小时。",
    "Plow 10 times.": "耕地 10 次。",
    "Reach acrobatics level 25": "达到杂技等级 25",
    "Reach alchemy level 25": "达到炼金等级 25",
    "Reach archery level 25": "达到箭术等级 25",
    "Reach axes level 25": "达到斧等级 25",
    "Reach crossbows level 25": "达到弩等级 25",
    "Reach excavation level 25": "达到挖掘等级 25",
    "Reach explorer level 10!": "达到探险等级 10！",
    "Reach farmer level 10!": "达到农业等级 10！",
    "Reach farmer level 25!": "达到农业等级 25！",
    "Reach fisherman level 10!": "达到渔夫等级 10！",
    "Reach fishing level 25": "达到钓鱼等级 25",
    "Reach herbalism level 25": "达到草药学等级 25",
    "Reach hunter level 5!": "达到猎人等级 5！",
    "Reach level 10.": "达到等级 10。",
    "Reach level 50.": "达到等级 50。",
    "Reach maces level 25": "达到重锤等级 25",
    "Reach miner level 15!": "达到矿工等级 15！",
    "Reach miner level 5!": "达到矿工等级 5！",
    "Reach mining level 25": "达到挖矿等级 25",
    "Reach power level 150": "达到综合等级 150",
    "Reach power level 300": "达到综合等级 300",
    "Reach power level 50": "达到综合等级 50",
    "Reach power level 500": "达到综合等级 500",
    "Reach repair level 25": "达到修复等级 25",
    "Reach salvage level 25": "达到回收等级 25",
    "Reach smelting level 25": "达到熔炼等级 25",
    "Reach swords level 25": "达到剑等级 25",
    "Reach taming level 25": "达到驯兽等级 25",
    "Reach tridents level 25": "达到三叉戟等级 25",
    "Reach unarmed level 25": "达到徒手等级 25",
    "Reach woodcutter level 8!": "达到伐木等级 8！",
    "Reach woodcutting level 25": "达到伐木等级 25",
    "Receive 10 pets.": "接收 10 只宠物。",
    "Repair an item.": "修复一件物品。",
    "Shear 100 sheep.": "剪 100 只羊的毛。",
    "Shoot 15 creepers.": "射杀 15 只苦力怕。",
    "Shoot 50 arrows.": "射出 50 支箭。",
    "Slay 100 skeletons.": "击杀 100 个骷髅。",
    "Sleep 5 times.": "睡觉 5 次。",
    "Sleep in a bed 50 times.": "在床上睡觉 50 次。",
    "Smelt 250 items.": "熔炼 250 个物品。",
    "Take part in the special 1MoreBlock event!": "参加 1MoreBlock 特别活动！",
    "Tame an animal.": "驯服一只动物。",
    "Teleport with ender pearls 10 times.": "用末影珍珠传送 10 次。",
    "Throw 1000 eggs.": "投掷 1000 个鸡蛋。",
    "Throw 1000 snowballs.": "投掷 1000 个雪球。",
    "Throw 2500 eggs.": "投掷 2500 个鸡蛋。",
    "Throw 5000 snowballs.": "投掷 5000 个雪球。",
    "Throw things at villagers.": "向村民投掷物品。",
    "Trade with a villager.": "与村民交易。",
    "Travel 100 Blocks with a minecart.": "乘坐矿车移动 100 格。",
    "Travel 100 Blocks with a pig.": "骑猪移动 100 格。",
    "Travel 1000 Blocks with your feet.": "步行移动 1000 格。",
    "Travel 150 blocks with a llama.": "骑羊驼移动 150 格。",
    "Travel 200 Blocks with a boat.": "乘船移动 200 格。",
    "Travel 500 Blocks with a horse.": "骑马移动 500 格。",
    "Travel 500 blocks whilst sneaking.": "潜行移动 500 格。",
    "Try to break granny's windows.": "试图打碎奶奶的窗户。",
    "Use /mcstats 30 times without spamming": "使用 /mcstats 30 次（请勿刷屏）",
    "Use a jukebox.": "使用唱片机。",
    "Use a magical trident.": "使用魔法三叉戟。",
    "Use bonemeal 15 times.": "使用骨粉 15 次。",
    "Win a raid.": "赢得一场袭击。",
    "Win ten raids.": "赢得十次袭击。",
    "You have to Die.": "你必须死亡。",
    "10 buckets filled with lava!": "装满 10 桶熔岩！",
    "10 pets received from friends!": "从好友处收到 10 只宠物！",
    "10 teleportations with ender pearls!": "用末影珍珠传送 10 次！",
    "100 sheep sheared!": "剪了 100 只羊！",
    "100 skeletons vanquished!": "击杀了 100 个骷髅！",
    "1000 eggs thrown!": "投掷了 1000 个鸡蛋！",
    "1000 snowballs thrown. That's the spirit!": "投掷了 1000 个雪球，精神可嘉！",
    "15 buckets filled with water!": "装满 15 桶水！",
    "15 creepers shot from a distance!": "从远处射杀 15 只苦力怕！",
    "20 advancements completed!": "完成了 20 个进度！",
    "25 endermen met their end!": "25 个末影人迎来了终结！",
    "250 items smelt in a furnace!": "在熔炉中熔炼了 250 个物品！",
    "3 pets given to friends!": "赠送了 3 只宠物给好友！",
    "5 objects enchanted!": "附魔了 5 次！",
    "50 arrows shot!": "射出了 50 支箭！",
    "500 deepslate blocks shattered!": "粉碎了 500 个深板岩！",
    "5000 snowballs? Blizzard incoming!": "5000 个雪球？暴风雪来了！",
    "A raid won!": "赢得一场袭击！",
    "Activated 10 mcMMO abilities!": "激活了 10 次 mcMMO 技能！",
    "Agriculture Legend!": "农业传奇！",
    "Brewed some trouble for those witches!": "给那些女巫惹了点麻烦！",
    "Buzzing with success!": "嗡嗡作响，大获成功！",
    "Cats everywhere!": "到处都是猫！",
    "Digging deep!": "挖得够深！",
    "Doing business with your first villager!": "与第一位村民做生意！",
    "Drinking weird beverages all the time...": "一直在喝奇怪的饮料……",
    "Fishmaster! Sushi night!": "钓鱼大师！寿司之夜！",
    "Green Thumb Unlocked!": "绿手指解锁！",
    "Hope you recycled all that glass!": "希望你把玻璃都回收了！",
    "Just had a snack!": "刚吃了点零食！",
    "Legendary digger!": "传奇挖掘者！",
    "Let them eat cake!": "让他们吃蛋糕吧！",
    "Level 10 reached!": "达到 10 级！",
    "Made 20 banners—decorate the world!": "制作了 20 面旗帜——装饰世界吧！",
    "Master of the seas!": "海洋之主！",
    "Next craft, Excalibur?": "下次合成，王者之剑？",
    "One hundred placed stones!": "放置了一百个石头！",
    "One jukebox used!": "使用了一次唱片机！",
    "One thousand placed stones!": "放置了一千个石头！",
    "Panda paradise achieved!": "熊猫天堂达成！",
    "Picasso would be proud.": "毕加索也会为你骄傲。",
    "Reached power level 150!": "达到综合等级 150！",
    "Reached power level 300!": "达到综合等级 300！",
    "Reached power level 50!": "达到综合等级 50！",
    "Reached power level 500!": "达到综合等级 500！",
    "Run the stats command 10 times!": "运行了 10 次统计命令！",
    "So social!": "真社交！",
    "Sticky situation!": "黏黏的情况！",
    "Ten raids!": "十次袭击！",
    "The first time you caught a fish!": "第一次钓到鱼！",
    "The first time you crafted a blade!": "第一次打造利刃！",
    "The first time you died!": "第一次死亡！",
    "The first time you killed a zombie!": "第一次击杀僵尸！",
    "The party never ends!": "派对永不结束！",
    "The world awaits!": "世界在等你！",
    "Timber!": "伐木！",
    "Voted 10 times for the server!": "为服务器投票 10 次！",
    "Welcome back - the server recognizes you big time!": "欢迎回来——服务器大大认可你！",
    "Wheee! Master of dreams": "哇！梦境大师",
    "Yippie! You killed the owner of the server!": "耶！你击杀了服务器服主！",
    "You are the ultimate defender!": "你是终极防御者！",
    "You bred your first sheep!": "你繁殖了第一只羊！",
    "You brewed your first potion!": "你酿造了第一瓶药水！",
    "You broke your favorite tool!": "你弄坏了最爱的工具！",
    "You built something... indestructible?": "你建造了……不可摧毁的东西？",
    "You connected to our server for the first time!": "你第一次连接我们的服务器！",
    "You discovered ancient tech!": "你发现了远古科技！",
    "You entered a bed 5 times!": "你睡了 5 次觉！",
    "You have broken 10 ice blocks!": "你破坏了 10 个冰块！",
    "You have broken 32 ice and snow, Woo!": "你破坏了 32 个冰和雪，哇！",
    "You have reached hunter level 5!": "你达到了猎人等级 5！",
    "You jumped as high as a kangaroo!": "你跳得像袋鼠一样高！",
    "You just repaired your first item!": "你刚修复了第一件物品！",
    "You lapidated villagers 10 times.": "你向村民投掷了 10 次。",
    "You launched 10 fireworks!": "你燃放了 10 次烟花！",
    "You lived to tell the tale!": "你活了下来，还能讲述这段经历！",
    "You might start a farm soon.": "你很快就要开农场了。",
    "You placed 25 crafting tables! Workbench Collector!": "你放置了 25 个工作台！工作台收藏家！",
    "You played for one hour on the server!": "你在服务器上游玩了一小时！",
    "You plowed the ground 10 times!": "你耕地了 10 次！",
    "You shot 100 projectiles at glass blocks!": "你向玻璃射出了 100 个弹射物！",
    "You tamed your first animal!": "你驯服了第一只动物！",
    "You took part in the special event!": "你参加了特别活动！",
    "You traveled 100 blocks in a minecart!": "你乘坐矿车移动了 100 格！",
    "You traveled 100 blocks on a pig!": "你骑猪移动了 100 格！",
    "You traveled 100 blocks with elytra!": "你用鞘翅飞行了 100 格！",
    "You traveled 1000 blocks by foot!": "你步行移动了 1000 格！",
    "You traveled 150 blocks on a llama!": "你骑羊驼移动了 150 格！",
    "You traveled 200 blocks in a boat!": "你乘船移动了 200 格！",
    "You traveled 500 blocks on a horse!": "你骑马移动了 500 格！",
    "You traveled 500 blocks whilst sneaking!": "你潜行移动了 500 格！",
    "You used bone meal on plants 15 times!": "你对植物使用了 15 次骨粉！",
    "You're saving the planet!": "你在拯救地球！",
    "You've become a master!": "你已成为大师！",
    "You've mastered the powers of the sea!": "你掌握了海洋之力！",
    "You've reached acrobatics level 25!": "你达到了杂技等级 25！",
    "You've reached alchemy level 25!": "你达到了炼金等级 25！",
    "You've reached archery level 25!": "你达到了箭术等级 25！",
    "You've reached axes level 25!": "你达到了斧等级 25！",
    "You've reached crossbows level 25!": "你达到了弩等级 25！",
    "You've reached excavation level 25!": "你达到了挖掘等级 25！",
    "You've reached fishing level 25!": "你达到了钓鱼等级 25！",
    "You've reached herbalism level 25!": "你达到了草药学等级 25！",
    "You've reached maces level 25!": "你达到了重锤等级 25！",
    "You've reached mining level 25!": "你达到了挖矿等级 25！",
    "You've reached repair level 25!": "你达到了修复等级 25！",
    "You've reached salvage level 25!": "你达到了回收等级 25！",
    "You've reached smelting level 25!": "你达到了熔炼等级 25！",
    "You've reached swords level 25!": "你达到了剑等级 25！",
    "You've reached taming level 25!": "你达到了驯兽等级 25！",
    "You've reached tridents level 25!": "你达到了三叉戟等级 25！",
    "You've reached unarmed level 25!": "你达到了徒手等级 25！",
    "You've reached woodcutting level 25!": "你达到了伐木等级 25！",
    "You've used an entire pot of ink!": "你用光了一整瓶墨水！",
    "Your first treasure from the sea!": "你从海中获得的第一个宝藏！",
    "§1Cave Apprentice!": "§1洞穴学徒！",
    "§1Taiga biome master!": "§1针叶林大师！",
    "§1The first time you went mining!": "§1第一次挖矿！",
    "§6You have placed 5 chests!": "§6你放置了 5 个箱子！",
    "§6You have placed 50 chests!": "§6你放置了 50 个箱子！",
    "§cYou're killing the planet!": "§c你在破坏地球！",
    "§eJust milked a cow!.... §cMOOW": "§e刚给牛挤了奶…… §c哞~",
    "Become the Stone God!": "成为石头之神！",
    "Broadcast": "全服广播",
    "Fame and Glory": "名誉与荣耀",
}

# 修正上面几处笔误（已在上方 inline 修正，此处保留占位）

MISSION_DISPLAY: dict[str, str] = {
    "Kill <amount> Zombies": "击杀 <amount> 只僵尸",
    "Kill <amount> Skeletons": "击杀 <amount> 只骷髅",
    "Kill <amount> Spiders": "击杀 <amount> 只蜘蛛",
    "Kill <amount> Creepers": "击杀 <amount> 只苦力怕",
    "Kill <amount> Endermen": "击杀 <amount> 个末影人",
    "Kill <amount> Blazes": "击杀 <amount> 个烈焰人",
    "Kill <amount> Witches": "击杀 <amount> 个女巫",
    "Kill <amount> Piglins": "击杀 <amount> 个猪灵",
    "Kill <amount> Magma Cubes": "击杀 <amount> 个岩浆怪",
    "Mine <amount> Copper Ore": "挖掘 <amount> 个铜矿",
    "Mine <amount> Coal Ore": "挖掘 <amount> 个煤矿",
    "Mine <amount> Iron Ore": "挖掘 <amount> 个铁矿",
    "Mine <amount> Gold Ore": "挖掘 <amount> 个金矿",
    "Mine <amount> Diamonds": "挖掘 <amount> 个钻石",
    "Mine <amount> Lapis Ore": "挖掘 <amount> 个青金石矿",
    "Mine <amount> Redstone Ore": "挖掘 <amount> 个红石矿",
    "Mine <amount> Nether Quartz": "挖掘 <amount> 个下界石英",
    "Mine <amount> Ancient Debris": "挖掘 <amount> 个远古残骸",
    "Break <amount> Oak Logs": "破坏 <amount> 个橡木原木",
    "Break <amount> Jungle Logs": "破坏 <amount> 个丛林原木",
    "Break <amount> Stone": "破坏 <amount> 个石头",
    "Break <amount> Dirt": "破坏 <amount> 个泥土",
    "Break <amount> Gravel": "破坏 <amount> 个沙砾",
    "Eat <amount> Bread": "食用 <amount> 个面包",
    "Eat <amount> Steaks": "食用 <amount> 块牛排",
    "Eat <amount> Golden Apples": "食用 <amount> 个金苹果",
    "Place <amount> Stone": "放置 <amount> 个石头",
    "Place <amount> Planks": "放置 <amount> 个木板",
    "Place <amount> Glass": "放置 <amount> 个玻璃",
    "Smelt <amount> Iron Ingots": "熔炼 <amount> 个铁锭",
    "Smelt <amount> Gold Ingots": "熔炼 <amount> 个金锭",
    "Craft <amount> Bread": "合成 <amount> 个面包",
    "Craft <amount> TNT": "合成 <amount> 个 TNT",
    "Fish <amount> Cod": "钓 <amount> 条鳕鱼",
    "Fish <amount> Salmon": "钓 <amount> 条鲑鱼",
    "Fish <amount> Pufferfish": "钓 <amount> 条河豚",
    "Enchant <amount> swords": "附魔 <amount> 把剑",
    "Enchant <amount> armors": "附魔 <amount> 件盔甲",
    "Breed <amount> Cows": "繁殖 <amount> 头牛",
    "Breed <amount> Pigs": "繁殖 <amount> 头猪",
    "Shear <amount> Sheep": "剪 <amount> 只羊的毛",
    "Tame <amount> Wolves": "驯服 <amount> 只狼",
    "Tame <amount> Cats": "驯服 <amount> 只猫",
    "Trade with Agriculture Villagers <amount> Times": "与农业村民交易 <amount> 次",
    "Change with Crafters Villagers <amount> Times": "与工匠村民交易 <amount> 次",
    "Deal <amount> Damage to sea creatures": "对海洋生物造成 <amount> 点伤害",
    "Deal <amount> Damage to nether creatures": "对下界生物造成 <amount> 点伤害",
    "Deal <amount> Damage to end creatures": "对末地生物造成 <amount> 点伤害",
    "Deal <amount> Damage to overworld animals": "对主世界动物造成 <amount> 点伤害",
    "Deal <amount> Damage to Flying creatures": "对飞行生物造成 <amount> 点伤害",
    "Take <amount> Damage from fall": "受到 <amount> 点摔落伤害",
    "Take <amount> Damage from fire": "受到 <amount> 点火焰伤害",
    "Die <amount> Times from explosion": "因爆炸死亡 <amount> 次",
    "Move <amount> Blocks": "移动 <amount> 格",
    "Swim <amount> Blocks": "游泳 <amount> 格",
    "Gain <amount> XP Points": "获得 <amount> 点 XP",
    "Play for <amount> Minutes": "游玩 <amount> 分钟",
}
MISSION_DISPLAY["Kill <amount> Magma Cubes"] = "击杀 <amount> 个岩浆怪"


def _replace_aa_fields(text: str) -> str:
    text = re.sub(r"^LanguageFileName: lang\.yml\s*$", "LanguageFileName: lang-CN.yml", text, flags=re.M)
    text = re.sub(r"^DateLocale: en\s*$", "DateLocale: zh", text, flags=re.M)
    text = re.sub(r'^RootAdvancementTitle:.*$', 'RootAdvancementTitle: "MCWWS / 成就"', text, flags=re.M)

    def repl(m: re.Match[str]) -> str:
        indent, key, val = m.group(1), m.group(2), m.group(3).strip()
        raw = val
        if (raw.startswith("'") and raw.endswith("'")) or (raw.startswith('"') and raw.endswith('"')):
            raw = raw[1:-1]
        if raw in AA_TEXT:
            # 保留 § 颜色码
            return f"{indent}{key}: {AA_TEXT[raw]}"
        return m.group(0)

    return re.sub(r"^(\s+)(Goal|Message|DisplayName|Display):\s*(.+)$", repl, text, flags=re.M)


def localize_aa_config() -> None:
    path = ROOT / "plugins/AdvancedAchievements/config.yml"
    path.write_text(_replace_aa_fields(path.read_text(encoding="utf-8")), encoding="utf-8")


def localize_missions() -> None:
    path = ROOT / "plugins/BattlePass-Fork/missions.yml"
    text = path.read_text(encoding="utf-8")
    for en, zh in MISSION_DISPLAY.items():
        text = text.replace(f'display-name: "{en}"', f'display-name: "{zh}"')
    path.write_text(text, encoding="utf-8")


def localize_betonquest_language() -> None:
    path = ROOT / "plugins/BetonQuest/config.yml"
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"^(\s+default:\s*)en-US\s*$", r"\1zh-CN", text, flags=re.M)
    path.write_text(text, encoding="utf-8")


def _simple_replace_pairs() -> list[tuple[str, str]]:
    """BattlePass messages / shop / rewards 常见英文 -> 中文（保留占位符与 gradient）。"""
    return [
        ("BATTLE PASS", "战斗通行证"),
        ("Battle Pass", "战斗通行证"),
        ("Battle Coins", "战斗币"),
        ("Premium Battle Pass", "高级战斗通行证"),
        ("Premium Pass", "高级通行证"),
        ("Daily Missions", "每日任务"),
        ("Daily Reward", "每日奖励"),
        ("Leaderboard", "排行榜"),
        ("Battle Pass Shop", "战斗通行证商店"),
        ("Battle Pass Leaderboard", "战斗通行证排行榜"),
        ("Your Progress", "你的进度"),
        ("Previous Page", "上一页"),
        ("Next Page", "下一页"),
        ("CLICK TO VIEW", "点击查看"),
        ("CLICK TO OPEN", "点击打开"),
        ("CLICK TO CLAIM!", "点击领取！"),
        ("ON COOLDOWN", "冷却中"),
        ("IN PROGRESS", "进行中"),
        ("COMPLETED", "已完成"),
        ("ALREADY CLAIMED", "已领取"),
        ("PREMIUM ONLY", "仅限高级通行证"),
        ("LOCKED", "未解锁"),
        ("Level %level% Reward", "等级 %level% 奖励"),
        ("Level %level% Premium Reward", "等级 %level% 高级奖励"),
        ("Top 10 Players", "前十名玩家"),
        ("Your Balance", "你的余额"),
        ("Back", "返回"),
        ("Return to Battle Pass", "返回战斗通行证"),
        ("Time Until Reset", "距离重置"),
        ("Rewards", "奖励"),
        ("Required Level", "所需等级"),
        ("Progress", "进度"),
        ("Reward", "奖励"),
        ("Resets in", "重置倒计时"),
        ("Season Ends", "赛季结束"),
        ("Next Coins", "下次发币"),
        ("Next distribution", "下次发放"),
        ("Premium Pass:", "高级通行证："),
        ("Level:", "等级："),
        ("XP:", "XP："),
        ("Battle Coins:", "战斗币："),
        ("Total Levels:", "累计等级："),
        ("THIS IS YOU!", "这是你！"),
        ("Keep grinding to beat them!", "继续加油超越他们！"),
        ("Complete missions to earn XP", "完成任务获得 XP"),
        ("and unlock amazing rewards!", "解锁丰厚奖励！"),
        ("Complete daily missions", "完成每日任务"),
        ("to earn bonus XP!", "获得额外 XP！"),
        ("View the top 10 players", "查看等级最高的十名玩家"),
        ("with highest battle pass levels!", "战斗通行证等级排行！"),
        ("Spend your Battle Coins on", "使用战斗币购买"),
        ("exclusive rewards and items!", "专属奖励与物品！"),
        ("Claim your daily XP bonus!", "领取每日 XP 奖励！"),
        ("You have already claimed", "你已经领取过"),
        ("your daily reward!", "每日奖励！"),
        ("Next claim", "下次领取"),
        ("Missions reset in:", "任务重置倒计时："),
        ("Complete missions before", "在任务重置前完成"),
        ("they reset to earn XP!", "以赚取 XP！"),
        ("Compete for the top spots", "争夺排行榜前列"),
        ("and earn Battle Coins daily!", "每日获得战斗币！"),
        ("Season ends", "赛季结束"),
        ("Next coins", "下次发币"),
        ("Earn more by staying", "保持在排行榜内"),
        ("in the top 10!", "以赚取更多战斗币！"),
        ("How to earn", "如何获得"),
        ("What they're for", "用途"),
        ("Be in the top 10 leaderboard", "进入排行榜前十"),
        ("Purchase exclusive items", "购买专属物品"),
        ("Get special perks", "获得特殊福利"),
        ("Show off your dedication!", "展示你的坚持！"),
        ("Only players can use this command!", "只有玩家可以使用此命令！"),
        ("You don't have permission to use this command!", "你没有权限使用此命令！"),
        ("Player not found!", "找不到该玩家！"),
        ("Invalid amount! Please enter a number.", "无效数量！请输入数字。"),
        ("Amount must be positive!", "数量必须为正数！"),
        ("Configuration reloaded!", "配置已重载！"),
        ("Battle Pass enabled successfully!", "战斗通行证已成功启用！"),
        ("LEVEL UP!", "升级！"),
        ("You are now level %level%", "你现在是等级 %level%"),
        ("NEW REWARDS!", "新奖励！"),
        ("You have new rewards available to claim!", "你有新奖励可领取！"),
        ("Welcome back!", "欢迎回来！"),
        ("You have %amount% rewards", "你有 %amount% 个奖励"),
        ("available!", "可领取！"),
        ("You have %amount% new rewards", "你有 %amount% 个新奖励"),
        ("to claim!", "待领取！"),
        ("MISSION COMPLETED:", "任务完成："),
        ("Daily missions have been reset!", "每日任务已重置！"),
        ("An administrator has reset the daily missions!", "管理员已重置每日任务！"),
        ("Missions have been successfully reset!", "任务已成功重置！"),
        ("has forcefully reset the daily missions!", "已强制重置每日任务！"),
        ("SEASON RESET", "赛季重置"),
        ("The Battle Pass season has ended! A new season begins now!", "战斗通行证赛季已结束！新赛季现在开始！"),
        ("FORCED SEASON RESET", "强制赛季重置"),
        ("An administrator has reset the Battle Pass season!", "管理员已重置战斗通行证赛季！"),
        ("WARNING:", "警告："),
        ("The season will be reset in 2 seconds. All player progress will be lost!", "赛季将在 2 秒后重置，所有玩家进度将丢失！"),
        ("Season has been successfully reset!", "赛季已成功重置！"),
        ("has forcefully reset the Battle Pass season!", "已强制重置战斗通行证赛季！"),
        ("Season ends in:", "赛季结束倒计时："),
        ("has completed the entire Battle Pass!", "已完成整个战斗通行证！"),
        ("has become a", "已成为"),
        ("LEGEND", "传奇"),
        ("by completing the Premium Battle Pass!", "——完成了高级战斗通行证！"),
        ("Season %season% has begun!", "第 %season% 赛季已开始！"),
        ("Free Rewards Claimed!", "免费奖励已领取！"),
        ("Premium Rewards Claimed!", "高级奖励已领取！"),
        ("You have already claimed this reward!", "你已经领取过此奖励！"),
        ("You cannot claim this reward!", "你无法领取此奖励！"),
        ("(Level %level% Required)", "（需要等级 %level%）"),
        ("(Dropped on ground)", "（掉落在地面）"),
        ("This reward has already been redeemed! If you believe this is an error, please contact our staff.", "此奖励已兑换！如有疑问请联系管理员。"),
        ("Daily Reward Claimed!", "每日奖励已领取！"),
        ("You received %amount% XP", "你获得了 %amount% XP"),
        ("You have already claimed your daily reward!", "你已经领取过每日奖励！"),
        ("XP EVENT STARTED!", "XP 活动开始！"),
        ("All mission XP is now", "所有任务 XP 现为"),
        ("for", "持续"),
        ("The XP event has ended.", "XP 活动已结束。"),
        ("Mission XP rewards are back to normal.", "任务 XP 奖励已恢复正常。"),
        ("The XP event has been stopped by an admin.", "管理员已停止 XP 活动。"),
        ("There is no active XP event.", "当前没有进行中的 XP 活动。"),
        ("Top 10 players are receiving their daily Battle Coins!", "前十名玩家正在领取每日战斗币！"),
        ("received", "获得"),
        ("Your Battle Coins:", "你的战斗币："),
        ("Insufficient Battle Coins!", "战斗币不足！"),
        ("Need:", "需要："),
        ("Have:", "拥有："),
        ("Purchase Successful!", "购买成功！"),
        ("Bought", "购买了"),
        ("for", "花费"),
        ("You already have the Premium Battle Pass!", "你已经拥有高级战斗通行证！"),
        ("PREMIUM ACTIVATED", "高级通行证已激活"),
        ("You now have access to all premium rewards!", "你现在可以领取所有高级奖励！"),
        ("Redeemed %amount% Battle Coins!", "兑换了 %amount% 战斗币！"),
        ("You have already reached the maximum level!", "你已经达到最高等级！"),
        ("XP BOOST!", "XP 加成！"),
        ("Consumed %items% elixir(s) and gained %amount% XP!", "消耗 %items% 瓶 elixir，获得 %amount% XP！"),
        ("XP EVENT!", "XP 活动！"),
        ("has activated a", "激活了"),
        ("2x XP Event", "2x XP 活动"),
        ("An XP event is already active!", "已有 XP 活动进行中！"),
        ("Available now!", "现在可用！"),
        ("Free", "免费"),
        ("Premium", "高级"),
        ("day", "天"),
        ("days", "天"),
        ("hour", "小时"),
        ("hours", "小时"),
        ("minute", "分钟"),
        ("minutes", "分钟"),
        ("Usage:", "用法："),
        ("Open the Battle Pass GUI", "打开战斗通行证界面"),
        ("Show this help menu", "显示帮助菜单"),
        ("Reload the configuration", "重载配置"),
        ("Force reset the season", "强制重置赛季"),
        ("Force reset daily missions", "强制重置每日任务"),
        ("Reset battle pass progress for a player", "重置玩家战斗通行证进度"),
        ("Give premium pass", "给予高级通行证"),
        ("Remove premium pass", "移除高级通行证"),
        ("Add XP to a player", "为玩家增加 XP"),
        ("Remove XP from a player", "为玩家减少 XP"),
        ("Add Battle Coins", "增加战斗币"),
        ("Remove Battle Coins", "减少战斗币"),
        ("Give custom items", "给予自定义物品"),
        ("Hide player from leaderboard", "从排行榜隐藏玩家"),
        ("Show player in leaderboard", "在排行榜显示玩家"),
        ("Edit rewards for a specific season", "编辑指定赛季奖励"),
        ("Start an XP multiplier event", "开始 XP 倍率活动"),
        ("Stop the current XP event", "停止当前 XP 活动"),
        ("Successfully reset battle pass progress for", "已成功重置战斗通行证进度："),
        ("Your Battle Pass progress has been reset by an admin!", "管理员已重置你的战斗通行证进度！"),
        ("BATTLE PASS COMMANDS", "战斗通行证命令"),
        ("CONGRATULATIONS", "恭喜"),
        ("You now have the Premium Battle Pass!", "你已获得高级战斗通行证！"),
        ("Your Premium Battle Pass has been removed!", "你的高级战斗通行证已被移除！"),
        ("You need the Premium Pass to claim this reward!", "领取此奖励需要高级通行证！"),
        ("Premium pass given to", "已给予高级通行证："),
        ("Premium pass removed from", "已移除高级通行证："),
        ("Added", "已增加"),
        ("Removed", "已减少"),
        ("to", "给"),
        ("from", "从"),
        ("only has", "只有"),
        ("Given", "已给予"),
        ("Some items dropped", "部分物品掉落在地面"),
        ("You received", "你获得了"),
        ("This mission is only available to", "此任务仅对"),
        ("players with", "拥有"),
        ("Battle Coins Info", "战斗币说明"),
        ("Battle Coins are special currency", "战斗币是特殊货币"),
        ("awarded to top players daily!", "每日奖励给排行榜前列玩家！"),
        ("#1 gets 10 coins", "#1 获得 10 战斗币"),
        ("#2 gets 9 coins", "#2 获得 9 战斗币"),
        ("... and so on", "……以此类推"),
        ("ACTIVE", "已激活"),
        ("INACTIVE", "未激活"),
        ("Iron Ingot", "铁锭"),
        ("Coal", "煤炭"),
        ("Redstone", "红石"),
        ("Lapis Lazuli", "青金石"),
        ("Experience Bottle", "经验瓶"),
        ("Emerald", "绿宝石"),
        ("Diamond", "钻石"),
        ("Iron Block", "铁块"),
        ("Gold Block", "金块"),
        ("Money", "金钱"),
        ("Ender Pearl", "末影珍珠"),
        ("Blaze Rod", "烈焰棒"),
        ("Ghast Tear", "恶魂之泪"),
        ("Magma Cream", "岩浆膏"),
        ("Quartz", "石英"),
        ("Glowstone", "荧石"),
        ("Prismarine Shard", "海晶碎片"),
        ("Prismarine Crystals", "海晶砂粒"),
        ("Slime Ball", "史莱姆球"),
        ("Gunpowder", "火药"),
        ("String", "线"),
        ("Spider Eye", "蜘蛛眼"),
        ("Shulker Shell", "潜影壳"),
        ("Phantom Membrane", "幻翼膜"),
        ("Nautilus Shell", "鹦鹉螺壳"),
        ("Rabbit Foot", "兔子脚"),
        ("Turtle Scute", "海龟鳞甲"),
        ("Enchanted Book", "附魔书"),
        ("XP Levels", "XP 等级"),
        ("Iron Horse Armor", "铁马铠"),
        ("Saddle", "鞍"),
        ("Name Tag", "命名牌"),
        ("Golden Carrot", "金胡萝卜"),
        ("Glistering Melon Slice", "闪烁的西瓜片"),
        ("Fermented Spider Eye", "发酵蛛眼"),
        ("Blaze Powder", "烈焰粉"),
        ("Ender Eye", "末影之眼"),
        ("Diamond Block", "钻石块"),
        ("Speed II (1 hour)", "速度 II（1 小时）"),
        ("Emerald Block", "绿宝石块"),
        ("Ancient Debris", "远古残骸"),
        ("Netherite Scrap", "下界合金碎片"),
        ("Crying Obsidian", "哭泣的黑曜石"),
        ("Netherite Ingot", "下界合金锭"),
        ("Golden Apple", "金苹果"),
        ("Enchanted Golden Apple", "附魔金苹果"),
        ("Beacon", "信标"),
        ("Elytra", "鞘翅"),
        ("Nether Star", "下界之星"),
        ("Dragon Head", "龙首"),
        ("Heart of the Sea", "海洋之心"),
        ("Totem of Undying", "不死图腾"),
        ("Fly Permission", "飞行权限"),
        ("Server Announcement", "全服公告"),
        ("Trident", "三叉戟"),
        ("Diamond Helmet", "钻石头盔"),
        ("Diamond Chestplate", "钻石胸甲"),
        ("Diamond Leggings", "钻石护腿"),
        ("Diamond Boots", "钻石靴子"),
        ("Netherite Upgrade Smithing Template", "下界合金升级锻造模板"),
        ("Diamond Horse Armor", "钻石马铠"),
        ("Dragon Egg", "龙蛋"),
        ("VIP Rank", "VIP 等级"),
        ("Legendary Crates", "传奇宝箱"),
        ("Netherite Helmet", "下界合金头盔"),
        ("Netherite Chestplate", "下界合金胸甲"),
        ("Netherite Leggings", "下界合金护腿"),
        ("Netherite Boots", "下界合金靴子"),
        ("Anvil", "铁砧"),
        ("Brewing Stand", "酿造台"),
        ("Ender Chest", "末影箱"),
        ("Shulker Box", "潜影盒"),
        ("Conduit", "潮涌核心"),
        ("Music Disc Pigstep", "音乐唱片 Pigstep"),
        ("Music Disc Otherside", "音乐唱片 Otherside"),
        ("Creeper Head", "苦力怕头颅"),
        ("Zombie Head", "僵尸头颅"),
        ("Skeleton Skull", "骷髅头颅"),
        ("Wither Skeleton Skull", "凋灵骷髅头颅"),
        ("Netherite Block", "下界合金块"),
        ("Regeneration II (2 hours)", "生命恢复 II（2 小时）"),
        ("Dragon Breath", "龙息"),
        ("End Crystal", "末地水晶"),
        ("Chorus Fruit", "紫颂果"),
        ("Netherite Sword", "下界合金剑"),
        ("VIP Kit Access", "VIP 工具包权限"),
        ("VIP Kit", "VIP 工具包"),
        ("Premium Kit", "高级工具包"),
    ]


def localize_battlepass_rewards() -> None:
    """仅替换 BattlePass 奖励文件中的 display 行。"""
    display_map = {
        "x16 Iron Ingot": "x16 铁锭",
        "x8 Iron Ingot": "x8 铁锭",
        "x32 Coal": "x32 煤炭",
        "x16 Redstone": "x16 红石",
        "x16 Lapis Lazuli": "x16 青金石",
        "x8 Experience Bottle": "x8 经验瓶",
        "$1000": "$1000",
        "x4 Emerald": "x4 绿宝石",
        "x2 Diamond": "x2 钻石",
        "x2 Iron Block": "x2 铁块",
        "x1 Gold Block": "x1 金块",
        "$5000 Money": "$5000 金钱",
        "x8 Ender Pearl": "x8 末影珍珠",
        "x4 Blaze Rod": "x4 烈焰棒",
        "x2 Ghast Tear": "x2 恶魂之泪",
        "x8 Magma Cream": "x8 岩浆膏",
        "x16 Experience Bottle": "x16 经验瓶",
        "$2500": "$2500",
        "x4 Diamond": "x4 钻石",
        "$10,000": "$10,000",
        "VIP Kit Access": "VIP 工具包权限",
        "x16 Slime Ball": "x16 史莱姆球",
        "x16 Gunpowder": "x16 火药",
        "x32 String": "x32 线",
        "x8 Spider Eye": "x8 蜘蛛眼",
        "x1 Shulker Shell": "x1 潜影壳",
        "x4 Phantom Membrane": "x4 幻翼膜",
        "x2 Nautilus Shell": "x2 鹦鹉螺壳",
        "x4 Rabbit Foot": "x4 兔子脚",
        "x2 Turtle Scute": "x2 海龟鳞甲",
        "x1 Enchanted Book": "x1 附魔书",
        "$7,500": "$7,500",
        "100 XP Levels": "100 级 XP",
        "x1 Iron Horse Armor": "x1 铁马铠",
        "x1 Saddle": "x1 鞍",
        "x2 Name Tag": "x2 命名牌",
        "x8 Golden Carrot": "x8 金胡萝卜",
        "x8 Glistering Melon Slice": "x8 闪烁的西瓜片",
        "x4 Fermented Spider Eye": "x4 发酵蛛眼",
        "x8 Blaze Powder": "x8 烈焰粉",
        "x2 Ender Eye": "x2 末影之眼",
        "x1 Diamond Block": "x1 钻石块",
        "$20,000": "$20,000",
        "Speed II (1 hour)": "速度 II（1 小时）",
        "x1 Emerald Block": "x1 绿宝石块",
        "x1 Ancient Debris": "x1 远古残骸",
        "x1 Netherite Scrap": "x1 下界合金碎片",
        "x8 Crying Obsidian": "x8 哭泣的黑曜石",
        "$30000": "$30,000",
        "x8 Diamond": "x8 钻石",
        "$5000": "$5000",
        "Premium Kit": "高级工具包",
        "x1 Netherite Ingot": "x1 下界合金锭",
        "x4 Golden Apple": "x4 金苹果",
        "x1 Enchanted Golden Apple": "x1 附魔金苹果",
        "x1 Beacon": "x1 信标",
        "$15,000": "$15,000",
        "x1 Elytra": "x1 鞘翅",
        "x2 Nether Star": "x2 下界之星",
        "x1 Dragon Head": "x1 龙首",
        "x1 Heart of the Sea": "x1 海洋之心",
        "x2 Totem of Undying": "x2 不死图腾",
        "$25,000": "$25,000",
        "Fly Permission": "飞行权限",
        "Server Announcement": "全服公告",
        "x1 Trident": "x1 三叉戟",
        "x1 Diamond Helmet": "x1 钻石头盔",
        "x1 Diamond Chestplate": "x1 钻石胸甲",
        "x1 Diamond Leggings": "x1 钻石护腿",
        "x1 Diamond Boots": "x1 钻石靴子",
        "x1 Netherite Upgrade Smithing Template": "x1 下界合金升级锻造模板",
        "x1 Diamond Horse Armor": "x1 钻石马铠",
        "x3 Enchanted Book": "x3 附魔书",
        "x64 Experience Bottle": "x64 经验瓶",
        "x1 Dragon Egg": "x1 龙蛋",
        "$50,000": "$50,000",
        "VIP Rank": "VIP 等级",
        "3x Legendary Crates": "3x 传奇宝箱",
        "x1 Netherite Helmet": "x1 下界合金头盔",
        "x1 Netherite Chestplate": "x1 下界合金胸甲",
        "x1 Netherite Leggings": "x1 下界合金护腿",
        "x1 Netherite Boots": "x1 下界合金靴子",
        "x2 Beacon": "x2 信标",
        "x3 Anvil": "x3 铁砧",
        "x3 Brewing Stand": "x3 酿造台",
        "x2 Ender Chest": "x2 末影箱",
        "x1 Shulker Box": "x1 潜影盒",
        "x1 Conduit": "x1 潮涌核心",
        "x1 Music Disc Pigstep": "x1 音乐唱片 Pigstep",
        "x1 Music Disc Otherside": "x1 音乐唱片 Otherside",
        "x1 Creeper Head": "x1 苦力怕头颅",
        "x1 Zombie Head": "x1 僵尸头颅",
        "x1 Skeleton Skull": "x1 骷髅头颅",
        "x3 Wither Skeleton Skull": "x3 凋灵骷髅头颅",
        "x3 Netherite Ingot": "x3 下界合金锭",
        "x1 Netherite Block": "x1 下界合金块",
        "x2 Elytra": "x2 鞘翅",
        "$75,000": "$75,000",
        "Regeneration II (2 hours)": "生命恢复 II（2 小时）",
        "x16 Dragon Breath": "x16 龙息",
        "x4 End Crystal": "x4 末地水晶",
        "x32 Chorus Fruit": "x32 紫颂果",
        "x3 Totem of Undying": "x3 不死图腾",
        "x4 Nether Star": "x4 下界之星",
        "x3 Enchanted Golden Apple": "x3 附魔金苹果",
        "x1 Netherite Sword": "x1 下界合金剑",
        "VIP Kit": "VIP 工具包",
    }
    for rel in [
        "plugins/BattlePass-Fork/BattlePassFREE.yml",
        "plugins/BattlePass-Fork/BattlePassPREMIUM.yml",
    ]:
        path = ROOT / rel
        lines = path.read_text(encoding="utf-8").splitlines()
        out = []
        for line in lines:
            m = re.match(r"^(\s*display:\s*)(.+)$", line)
            if m:
                prefix, val = m.group(1), m.group(2).strip().strip('"')
                if val in display_map:
                    out.append(f'{prefix}"{display_map[val]}"')
                    continue
            out.append(line)
        path.write_text("\n".join(out) + "\n", encoding="utf-8")


def main() -> None:
    localize_aa_config()
    localize_missions()
    localize_betonquest_language()
    localize_battlepass_rewards()
    print("localized: AdvancedAchievements, BattlePass missions/rewards, BetonQuest language")


if __name__ == "__main__":
    main()
