name: MCWWS_UltimateAdvancements
main: work.mcwws.ultimateadvancements.McwwsUltimateAdvancementsPlugin
version: 1.0.0
api-version: '1.21'
depend: [UltimateAdvancementAPI]
description: 使用 UltimateAdvancementAPI 注册“流浪世界”第一棵进度树

