name: BookNews
main: com.gmail.legamemc.booknews.Main
author: LegameMc
version: '6.26'
api-version: 1.13
softdepend: [PlaceholderAPI]
commands:
    booknews:
        description: Admin Command
        usage: /<command> [reload|news]
    news:
        description: Check News
        usage: /<command>